### ISSUE TITLE
Remove dep. on perbu/tusd

### ISSUE THREAD

**Issue by perbu** [arkivverket/mottak#165]
Just a reminder that you should perhaps clone my repo into arkivverket so build doesn't break if my account changes.

Kos og klemz.

Per.

**Comment by omBratteng** [comment]
@perbu I have forked upstream tusd, and re-implemented the Azure store.
https://github.com/tus/tusd/pull/458
Just waiting for an approval from @Acconut

Dropping the support for AppendBlob, as it's more suited for logs, and no more issue with chunks >4 MiB and files >195 GiB
